### ISSUE TITLE
pagemirror svg failure

### ISSUE THREAD

**Issue by jiangts** [rafaelw/mutation-summary#23]
I was trying the PageMirror extension a several pages, and upon trying http://snapsvg.io/#, I found that the SVG was not being rendered on the mirror!

original page:
![image](https://cloud.githubusercontent.com/assets/4052045/12973275/01b8d5c6-d060-11e5-8f2d-a117b20d6ef7.png)

mirrored page:
![image](https://cloud.githubusercontent.com/assets/4052045/12973279/070b05b2-d060-11e5-94ba-67412f974c56.png)

Instead, as you can see, the <desc> text of the svg element is displayed.
Looking in the DOM, I see that the svg tag and all it's children are indeed mirrored into the mirror's DOM. I just don't understand why they don't display.

**Comment by catz85** [comment]
Hi @jiangts do you know how to fix this issue?

**Comment by jiangts** [comment]
no, but I found a workaround

**Comment by sato-shi** [comment]
Hi @jiangts, i am trying to find a solution for the same issue.  Can you please share your workaround?

**Comment by jiangts** [comment]
use a tool like https://github.com/gabelerner/canvg to convert it to an image!
